#!/bin/bash

#    ▖  ▖  ▜ ▜             
#    ▌▞▖▌▀▌▐ ▐ █▌▛▘        
#    ▛ ▝▌█▌▐▖▐▖▙▖▌         
#                          
#    ▗▄▖▜       ▄▖▄▖▖▖   ▄▖
#    ▌▄▐▐ ▀▌▛▘█▌▄▌▙▖▙▌  ▘▄▌
#    ▌▀▀▐▖█▌▌ ▙▖▄▌▄▌ ▌  ▖▄▌
#     ▀                                                                                    


confDir=$HOME/.config/waller
conf=$confDir/waller.conf
rasi=$confDir/waller.rasi

rofiCmd="rofi -dmenu -theme ${rasi}"

. $conf


# Select a picture with rofi
wallSelection=$(for wall in "$wallsDir"*; do echo -en "$wall\0icon\x1fthumbnail://$wall\n" ; done | $rofiCmd)

# Set the wallpaper
[[ -n "$wallSelection" ]] || exit 1

if ! $blur; then
	awww img ${wallSelection}
	exit 0	
fi

blurLvl="0x4"

if ! $softBlur; then
	blurLvl="0x8"
fi

magick ${wallSelection} -scale 50% -blur "${blurLvl}" -resize 200% ${confDir}/.tmp 
awww img ${confDir}/.tmp

exit 0
